# Generated by Django 2.2 on 2019-06-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название экскурсии', max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('manager', models.CharField(max_length=200, verbose_name='Менеджер группы туристов')),
                ('manager_phone', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('r', 'сформирована'), ('e', 'на экскурсии')], default='r', help_text='Статус групп туристов', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название отеля', max_length=300)),
                ('addres', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('cost_for_one_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Питание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО Туриста')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='email')),
                ('date_of_arrival', models.DateField(verbose_name='Дата прибытия')),
                ('date_of_departure', models.DateField(verbose_name='Дата убытия')),
                ('note', models.TextField(max_length=1000, verbose_name='Примечание')),
                ('status', models.CharField(blank=True, choices=[('r', 'заявка сформирована'), ('c', 'оплачено'), ('d', 'пакет документов готов'), ('g', 'в группе'), ('h', 'заселен в отель'), ('e', 'на экскурсии')], default='r', max_length=1, verbose_name='Статус туриста')),
                ('excursion', models.ManyToManyField(to='tourists.Excursion', verbose_name='Экскурсии')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Group', verbose_name='Группа')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Hotel', verbose_name='Отель')),
                ('nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Nutrition', verbose_name='Питание')),
            ],
            options={
                'ordering': ['date_of_arrival'],
                'permissions': (('can_edit', 'Editing data'), ('can_get_report', 'Getting report')),
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='tourist', verbose_name='Файл')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
