# Generated by Django 2.2.2 on 2019-06-25 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatelineForHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, verbose_name='Дата заселения')),
                ('date_to', models.DateField(blank=True, verbose_name='Дата выселения')),
            ],
            options={
                'verbose_name_plural': 'Временная ось для пребывания в отелях',
                'get_latest_by': 'date_from',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название экскурсии', max_length=300)),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('manager', models.CharField(max_length=200, verbose_name='Менеджер группы туристов')),
                ('manager_phone', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('r', 'сформирована'), ('e', 'на экскурсии')], default='r', help_text='Статус групп туристов', max_length=1)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название питания', max_length=300)),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Питание',
                'verbose_name_plural': 'Питание',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО Туриста')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='email')),
                ('date_of_arrival', models.DateField(blank=True, verbose_name='Дата прибытия')),
                ('date_of_departure', models.DateField(blank=True, verbose_name='Дата убытия')),
                ('note', models.TextField(max_length=150, verbose_name='Примечание')),
                ('status', models.CharField(blank=True, choices=[('r', 'заявка сформирована'), ('c', 'оплачено'), ('d', 'пакет документов готов'), ('g', 'в группе'), ('h', 'заселен в отель'), ('e', 'на экскурсии')], default='r', max_length=1, verbose_name='Статус туриста')),
                ('visa', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия визы')),
                ('contract', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия договора')),
                ('passport', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия паспорта')),
                ('others', models.FileField(blank=True, null=True, upload_to='files', verbose_name='Другие документы')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
        migrations.CreateModel(
            name='TimelineForNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField(default=datetime.datetime(2019, 6, 25, 13, 10, 3, 901638), verbose_name='Начало')),
                ('time_to', models.DateTimeField(default=datetime.datetime(2019, 6, 25, 13, 10, 3, 901732), verbose_name='Окончание')),
                ('nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Nutrition')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist')),
            ],
            options={
                'verbose_name_plural': 'Временная ось для питания',
                'get_latest_by': 'date_from',
            },
        ),
        migrations.CreateModel(
            name='TimelineForExcursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateTimeField(verbose_name='начало экскурсии')),
                ('time_to', models.DateTimeField(verbose_name='окончание экскурсии')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Excursion')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist')),
            ],
            options={
                'verbose_name_plural': 'Временная ось для экскурсий',
                'get_latest_by': 'date_from',
            },
        ),
        migrations.AddField(
            model_name='nutrition',
            name='timelines',
            field=models.ManyToManyField(through='tourists.TimelineForNutrition', to='tourists.Tourist'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название отеля', max_length=300, verbose_name='Название отеля')),
                ('addres', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('cost_for_one_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('datelines', models.ManyToManyField(through='tourists.DatelineForHotel', to='tourists.Tourist')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.AddField(
            model_name='excursion',
            name='timelines',
            field=models.ManyToManyField(through='tourists.TimelineForExcursion', to='tourists.Tourist'),
        ),
        migrations.AddField(
            model_name='datelineforhotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Hotel'),
        ),
        migrations.AddField(
            model_name='datelineforhotel',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist'),
        ),
    ]
