# Generated by Django 2.2.2 on 2019-06-25 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 13, 10, 27, 694026), verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 13, 10, 27, 694189), verbose_name='Окончание'),
        ),
    ]
