# Generated by Django 2.2 on 2019-06-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='hotel',
        ),
        migrations.AddField(
            model_name='tourist',
            name='hotel',
            field=models.ManyToManyField(to='tourists.Hotel', verbose_name='Отель'),
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='tourist',
            name='nutrition',
            field=models.ManyToManyField(to='tourists.Nutrition', verbose_name='Питание'),
        ),
    ]
