# Generated by Django 2.2 on 2019-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0002_auto_20190611_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'заявка сформирована'), ('c', 'оплачено'), ('d', 'пакет документов готов'), ('g', 'в группе'), ('h', 'заселен в отель'), ('e', 'на экскурсии')], default='r', help_text='Статус туриста', max_length=1),
        ),
    ]
