# Generated by Django 2.2.2 on 2019-06-25 03:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0002_auto_20190625_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinefornutrition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Group'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 13, 13, 59, 98982), verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 25, 13, 13, 59, 99161), verbose_name='Окончание'),
        ),
    ]
