# Generated by Django 2.2 on 2019-06-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0002_auto_20190616_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='full_package_of_documents',
            field=models.BooleanField(blank=True, null=True, verbose_name='Полный пакет документов'),
        ),
    ]
