# Generated by Django 2.2.2 on 2019-06-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0003_auto_20190625_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineforexcursion',
            options={'get_latest_by': 'date_from', 'verbose_name_plural': 'Время для экскурсий'},
        ),
        migrations.AlterModelOptions(
            name='timelinefornutrition',
            options={'get_latest_by': 'date_from', 'verbose_name_plural': 'Время для питания'},
        ),
        migrations.AddField(
            model_name='timelineforexcursion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='group',
            name='manager',
            field=models.CharField(blank=True, max_length=200, verbose_name='Менеджер группы туристов'),
        ),
        migrations.AlterField(
            model_name='group',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(blank=True, choices=[('f', 'формируется'), ('r', 'сформирована')], default='r', help_text='Статус групп туристов', max_length=1),
        ),
        migrations.AlterField(
            model_name='timelineforexcursion',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Excursion', verbose_name='Экскурсии'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Nutrition', verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_from',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_to',
            field=models.DateTimeField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist', verbose_name='Турист'),
        ),
    ]
