# Generated by Django 2.2 on 2019-06-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0003_tourist_full_package_of_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='time_begin',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='time_end',
        ),
        migrations.AddField(
            model_name='excursion',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='full_package_of_documents',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Полный пакет документов'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='note',
            field=models.TextField(max_length=500, verbose_name='Примечание'),
        ),
    ]
