# Generated by Django 2.2 on 2019-06-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0003_auto_20190612_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='excursion',
        ),
        migrations.AddField(
            model_name='tourist',
            name='excursion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Excursion'),
        ),
    ]
