# Generated by Django 2.2 on 2019-06-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0004_auto_20190612_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='date_of_arrival',
            field=models.DateField(verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='date_of_departure',
            field=models.DateField(verbose_name='Дата убытия'),
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='excursion',
        ),
        migrations.AddField(
            model_name='tourist',
            name='excursion',
            field=models.ManyToManyField(to='tourists.Excursion', verbose_name='Экскурсии'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourists.Hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО Туриста'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='note',
            field=models.TextField(max_length=1000, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
