# Generated by Django 2.2 on 2019-06-16 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0004_auto_20190616_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Копия договора'),
        ),
        migrations.AddField(
            model_name='files',
            name='others',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Другие документы'),
        ),
        migrations.AddField(
            model_name='files',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Копия паспорта'),
        ),
        migrations.AddField(
            model_name='files',
            name='visa',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Копия визы'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourists.Files'),
        ),
    ]
