# Generated by Django 2.2 on 2019-06-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0005_auto_20190616_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='file',
        ),
        migrations.AddField(
            model_name='tourist',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract', verbose_name='Копия договора'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='others',
            field=models.FileField(blank=True, null=True, upload_to='others', verbose_name='Другие документы'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='passport', verbose_name='Копия паспорта'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='visa',
            field=models.FileField(blank=True, null=True, upload_to='visa', verbose_name='Копия визы'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
