# Generated by Django 2.2 on 2019-06-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0006_auto_20190617_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='full_package_of_documents',
        ),
        migrations.AlterField(
            model_name='tourist',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия договора'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='others',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Другие документы'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия паспорта'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='visa',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='Копия визы'),
        ),
    ]
