# Generated by Django 2.2 on 2019-06-19 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0008_auto_20190618_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='time_to',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='time_to',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='nutrition',
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateField()),
                ('time_to', models.DateField()),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Nutrition')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist')),
            ],
        ),
        migrations.AddField(
            model_name='nutrition',
            name='timelines',
            field=models.ManyToManyField(through='tourists.Timeline', to='tourists.Tourist'),
        ),
    ]
