# Generated by Django 2.2 on 2019-06-19 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0009_auto_20190619_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeline',
            new_name='TimelineForNutrition',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='hotel',
            new_name='hotels',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='timelines',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='excursion',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='group',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='timeline',
            field=models.ManyToManyField(through='tourists.TimelineForNutrition', to='tourists.Tourist'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='name',
            field=models.CharField(help_text='Введите название питания', max_length=300),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='date_of_arrival',
            field=models.DateField(blank=True, verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='date_of_departure',
            field=models.DateField(blank=True, verbose_name='Дата убытия'),
        ),
        migrations.CreateModel(
            name='TimelineForExcursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.DateField()),
                ('time_to', models.DateField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Excursion')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist')),
            ],
        ),
        migrations.AddField(
            model_name='excursion',
            name='timeline',
            field=models.ManyToManyField(through='tourists.TimelineForExcursion', to='tourists.Tourist'),
        ),
    ]
