# Generated by Django 2.2 on 2019-06-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0010_auto_20190619_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='timeline',
            new_name='timelines',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='timeline',
            new_name='timelines',
        ),
    ]
