# Generated by Django 2.2.2 on 2019-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0011_auto_20190619_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineforexcursion',
            name='time_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timelineforexcursion',
            name='time_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timelinefornutrition',
            name='time_to',
            field=models.DateTimeField(),
        ),
    ]
