# Generated by Django 2.2 on 2019-06-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0012_auto_20190619_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='hotels',
        ),
        migrations.CreateModel(
            name='DatelineForHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Hotel')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourists.Tourist')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='datelines',
            field=models.ManyToManyField(through='tourists.DatelineForHotel', to='tourists.Tourist'),
        ),
    ]
