# Generated by Django 2.2.2 on 2019-06-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0013_auto_20190620_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='datelineforhotel',
            name='amount',
            field=models.DecimalField(decimal_places=4, default='100', max_digits=11),
        ),
    ]
